packages:
    - 'apps/*'
    - 'packages/*'

catalog:
    '@base-ui/react': '^1.2.0'
    '@gsap/react': '^2.1.2'
    '@google-cloud/recaptcha-enterprise': ^6.4.0
    '@hookform/resolvers': ^5.2.2
    '@icons-pack/react-simple-icons': '^13.8.0'
    '@t3-oss/env-core': '^0.13.8'
    '@t3-oss/env-nextjs': '^0.13.8'
    '@tailwindcss/cli': '^4.1.18'
    '@tailwindcss/postcss': '^4'
    '@tanstack/react-query': ^5.94.5
    '@lucide/lab': '^0.1.2'
    'framer-motion': ^12.38.0
    'zod': '^4.1.13'
    'vaul': '^1.1.2'
    'date-fns': '^4.1.0'
    'three': '^0.182.0'
    'qrcode': '^1.5.4'
    'cookies-next': '^6.1.1'
    'gsap': '^3.14.2'
    'motion': '^12.23.26'
    'clsx': '^2.1.1'
    'postcss': '^8.5.3'
    'autoprefixer': '^10.4.20'
    'sonner': ^2.0.7
    'react-hook-form': ^7.72.0
    'react-transition-progress': ^0.0.4
    'tailwindcss': '^4.1.5'
    'tailwindcss-animate': '^1.0.7'
    'tailwind-merge': '^3.4.0'
    'tailwind-variants': '^3.2.2'
    'tailwind-scrollbar-hide': '^4.0.0'
    'lucide-react': '^0.561.0'
    'dotenv': '^17.2.3'
    'eslint': '^9.39.1'
    'prettier': '^3.7.4'
    'eslint-config-next': '^16.0.10'
    'eslint-config-prettier': '^10.1.8'
    'eslint-plugin-prettier': '^5.5.4'
    'babel-plugin-react-compiler': '^1.0.0'
    'bunchee': '^6.6.2'
    'typescript': '^5.9.3'

catalogs:
    node-20:
        '@types/node': '^20'
    react-19:
        'react': '^19.2.1'
        'react-dom': '^19.2.1'
        '@types/react': '^19'
        '@types/react-dom': '^19'
    next-16:
        'next': '^16.1.6'
        '@next/env': '^16.1.6'
        'next-intl': '^4.8.2'
        'next-themes': '^0.4.6'
    types:
        '@types/three': '^0.182.0'
        '@types/qrcode': '^1.5.6'
